services:
  # redis:
  #   image: redis:7.2.4-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s

  lipikaar_server:
    image: abhilakshsinghreen/lipikaar_server:latest
    container_name: lipikaar_server
    ports:
      - "8000:8000"
    restart: always
    # depends_on:
    #   - redis
    volumes:
      - ./volumes/server:/app/volume
